### ISSUE TITLE
Error when running tutorial notebook

### ISSUE THREAD

**Issue by nordam** [ideaconsult/notebooks-ambit#1]
Hi,

I work in the NanoInformaTIX project, and I try to run through the tutorial notebook, but I get an error when running the third cell with code:

```
Select eNanoMapper database instance:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/s0/922ys9391_b7hp812fj69nfc0000gn/T/ipykernel_45370/3957739543.py in <module>
     12 
     13 style = {'description_width': 'initial'}
---> 14 config,config_servers, config_security, auth_object, msg = aa.parseOpenAPI3(config=config)
     15 service_widget = widgets.Dropdown(
     16     options=config_servers['url'],

~/anaconda3/envs/notebooks-ambit/lib/python3.10/site-packages/pynanomapper/aa.py in parseOpenAPI3(url, config, auth)
     43 def parseOpenAPI3(url='https://search.data.enanomapper.net/api-docs/', config='solr.yaml',auth="enmKeyAuth"):
     44     apikey=None
---> 45     config = yaml.load(requests.get(url+config).text)
     46     config_servers = json_normalize(config['servers'], None, ['url'])
     47     if 'securitySchemes' in config['components']:

TypeError: load() missing 1 required positional argument: 'Loader'
```

I'm afraid I don't understand much of the error message, other than that the problem appears to be in the file ```pynanomapper/aa.py```. Does this work for you? I set up the environment with conda, using the ```environment.yml``` file as described in the readme. It doesn't look like a python version has been specified, but in my case the one installed in the environment is 3.10. I'm also on a Mac, in case that's relevant.

**Comment by vedina** [comment]
it seems it's due to a newer yaml dependency than when the notebook was tested;  
now plain yaml.load() is deprecated  https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

@kerberizer guess we need to upgrade pynanomapper

**Comment by kerberizer** [comment]
@nordam Could you please run again `conda env update -f environment.yml` and then try again? If it still doesn't work, please check if `pip show pynanomapper` shows the version as `1.0.5`.
